import type { Metadata } from "next";
import { zenMaruGothic } from "./fonts/zenFont";
import { Theme } from "@radix-ui/themes";
import Header from "./components/ui/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={zenMaruGothic.className}>
        <Theme>
          <Header />
          {children}
        </Theme>
      </body>
    </html>
  );
}
